import Head from 'next/head'
import Title from '../components/global/title/Title'
import { FC, useContext } from 'react'
import styles from '../styles/Home.module.css'

const Home: FC = () => {
	//to do add translations
	return (
		<div className={styles.container}>
			<Head>
				<title>Coder2195 - Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Title>Coder2195's Website</Title>
		</div>
	)
}

export default Home
