import Head from 'next/head'
import Title from '../components/global/title/Title'
import { FC, useContext } from 'react'
import styles from '../styles/Home.module.css'
import TRANSLATIONS from '../translations/translation'
import { useLanguage } from './_app'

const Home: FC = () => {
	//to do add translations
	const { language } = useLanguage()
	return (
		<div className={styles.container}>
			<Head>
				<title>Coder2195's Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Title>{TRANSLATIONS[language].homeHeading}</Title>
		</div>
	)
}

export default Home
